from .gamma_correction_node import (
    NODE_CLASS_MAPPINGS as GAMMA_CORRECTION_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GAMMA_CORRECTION_NODE_DISPLAY_NAME_MAPPINGS,
)

from .iec_gamma_correction_node import (
    NODE_CLASS_MAPPINGS as IEC_GAMMA_CORRECTION_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IEC_GAMMA_CORRECTION_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **GAMMA_CORRECTION_NODE_CLASS_MAPPINGS,
    **IEC_GAMMA_CORRECTION_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **GAMMA_CORRECTION_NODE_DISPLAY_NAME_MAPPINGS,
    **IEC_GAMMA_CORRECTION_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
