from .lut_color_manipulation_node import (
    NODE_CLASS_MAPPINGS as _LUT_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _LUT_NAMES,
)
from .personal_lut_color_manipulation import (
    NODE_CLASS_MAPPINGS as _PERSONAL_LUT_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _PERSONAL_LUT_NAMES,
    WEB_DIRECTORY as _PERSONAL_LUT_WEB_DIRECTORY
)
from .saturation_hsv_node import (
    NODE_CLASS_MAPPINGS as _SATURATION_HSV_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _SATURATION_HSV_NAMES,
)
from .temperature_simple_node import (
    NODE_CLASS_MAPPINGS as _TEMPERATURE_SIMPLE_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _TEMPERATURE_SIMPLE_NAMES,
)
from .temperature_tanner_helland_node import (
    NODE_CLASS_MAPPINGS as _TEMPERATURE_TANNER_HELLAND_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _TEMPERATURE_TANNER_HELLAND_NAMES,
)

NODE_CLASS_MAPPINGS = {**_LUT_NODES, **_PERSONAL_LUT_NODES, **_SATURATION_HSV_NODES, **_TEMPERATURE_SIMPLE_NODES, **_TEMPERATURE_TANNER_HELLAND_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_LUT_NAMES, **_PERSONAL_LUT_NAMES, **_SATURATION_HSV_NAMES, **_TEMPERATURE_SIMPLE_NAMES, **_TEMPERATURE_TANNER_HELLAND_NAMES}
WEB_DIRECTORY = _PERSONAL_LUT_WEB_DIRECTORY

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
