from .bilinear_node import (
    NODE_CLASS_MAPPINGS as _BILINEAR_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _BILINEAR_NAMES,
)
from .malvar_he_culter_node import (
    NODE_CLASS_MAPPINGS as _MHC_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _MHC_NAMES,
)

NODE_CLASS_MAPPINGS = {**_BILINEAR_NODES, **_MHC_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_BILINEAR_NAMES, **_MHC_NAMES}
